# Non Negative Matrix Factorization (NMF)

NMF is an algorithm in multivariate analysis and linear algebra in which a matrix X is broken into product of 2 smaller matrices W and H, with the property that all the elements in the 3 matrices are non negative numbers. 

X = WH





In [0]:
import numpy as np
import pandas as pd
from sklearn.decomposition import NMF

In [0]:
# Creating a matrix of 6x6 from 6 lists

I1 = [2, 4, 3, 0, 3, 5]
I2 = [0, 5, 2, 4, 5, 4]
I3 = [0, 4, 1, 3, 0, 1]
I4 = [1, 0, 5, 5, 5, 1]
I5 = [0, 2, 4, 3, 1, 4]
I6 = [0, 1, 2, 5, 1, 0]
X = np.array([I1, I2, I3, I4, I5, I6]).transpose()
print(X)

[[2 0 0 1 0 0]
 [4 5 4 0 2 1]
 [3 2 1 5 4 2]
 [0 4 3 5 3 5]
 [3 5 0 5 1 1]
 [5 4 1 1 4 0]]


Usually, NMF is considered as breaking a given matrix into 2 matrices with $1^{st}$ matrix  as tall and skinny matrix while $2^{nd}$ matrix as fat and short matrix.

![alt text](https://drive.google.com/uc?id=1XUJo974yH7ZgkkYhgCdhNpYdR8MfuQe2)


### Breaking the 6x6 matrix into 6x3 and 3x6 matrices

In [0]:
model = NMF(random_state = 0, init = 'random', n_components = 3, alpha = 0, l1_ratio = 0)
# alpha is a constant that multiplies the regdularization terms. Set it to zero to have no regularization.
# l1_taio is for regularisation. If it is 0, then l2 is used. If it is 1, then l1 is used. If it is between 0 and 1 then penalty is a combination of l1 and l2. 
W = model.fit_transform(X)
H = model.components_
print('The W matrix is:\n', W.round(3))
print('The H matrix is:\n', H.round(3))

The W matrix is:
 [[0.515 0.    0.   ]
 [0.    0.12  2.866]
 [1.355 1.044 0.   ]
 [0.    2.653 0.164]
 [1.719 0.611 0.   ]
 [0.901 0.    1.833]]
The H matrix is:
 [[2.098 1.527 0.    2.047 1.096 0.   ]
 [0.    1.331 1.011 1.937 1.122 1.871]
 [1.48  1.617 1.121 0.    0.937 0.192]]


In [0]:
Y = np.dot(W,H)
print(Y.round(3))
print(np.sum(abs(X - Y)).round(3))

[[1.081 0.786 0.    1.054 0.564 0.   ]
 [4.24  4.794 3.333 0.232 2.821 0.775]
 [2.843 3.457 1.055 4.795 2.655 1.953]
 [0.242 3.796 2.866 5.139 3.13  4.996]
 [3.607 3.438 0.618 4.703 2.569 1.144]
 [4.603 4.34  2.055 1.845 2.706 0.352]]
17.916


### Breaking the 6x6 matrix into 6x4 and 4x6 matrices.

In [0]:
model = NMF(random_state = 0, init = 'random', n_components = 4, alpha = 0, l1_ratio = 0)
W1 = model.fit_transform(X)
H1 = model.components_
print('The W matrix is:\n', W1.round(3))
print('The H matrix is:\n', H1.round(3))

The W matrix is:
 [[0.345 0.    0.459 0.   ]
 [0.    0.    1.455 2.158]
 [0.836 1.7   1.078 0.   ]
 [0.    2.687 0.    1.27 ]
 [2.421 0.535 0.109 0.   ]
 [0.776 0.    2.085 0.819]]
The H matrix is:
 [[1.124 1.981 0.    1.67  0.112 0.   ]
 [0.    0.306 0.372 1.931 1.146 1.513]
 [2.023 0.033 0.    0.    1.678 0.   ]
 [0.318 2.403 1.728 0.    0.    0.482]]


In [0]:
Y1 = np.dot(W1,H1)
print(Y1.round(3))
print(np.sum(abs(X - Y1)).round(3))

[[1.317 0.699 0.    0.576 0.809 0.   ]
 [3.63  5.236 3.729 0.    2.442 1.04 ]
 [3.12  2.211 0.632 4.678 3.851 2.571]
 [0.403 3.874 3.193 5.188 3.08  4.677]
 [2.944 4.963 0.199 5.077 1.069 0.809]
 [5.35  3.575 1.415 1.295 3.586 0.395]]
9.954


### Breaking the 6x6 matrix into 6x5 and 5x6 matrices.

In [0]:
model = NMF(random_state = 0, init = 'random', n_components = 5, alpha = 0, l1_ratio = 0)
W2 = model.fit_transform(X)
H2 = model.components_
print('The W matrix is:\n', W2.round(3))
print('The H matrix is:\n', H2.round(3))

The W matrix is:
 [[0.    0.    0.012 0.    0.718]
 [0.    0.    1.407 2.471 0.215]
 [0.756 1.96  1.023 0.    0.332]
 [0.    2.794 0.    2.25  0.   ]
 [2.333 0.735 0.    0.    1.105]
 [1.329 0.    2.322 0.    0.   ]]
The H matrix is:
 [[0.    2.143 0.    0.871 0.126 0.   ]
 [0.    0.    0.108 1.85  1.094 1.26 ]
 [2.172 0.47  0.516 0.    1.605 0.   ]
 [0.08  1.766 1.267 0.    0.    0.519]
 [2.721 0.    0.013 1.443 0.    0.   ]]


In [0]:
Y2 = np.dot(W2,H2)
print(Y2.round(3))
print(np.sum(abs(X - Y2)).round(3))

[[1.981 0.006 0.015 1.037 0.019 0.   ]
 [3.837 5.025 3.859 0.31  2.259 1.283]
 [3.126 2.102 0.744 4.765 3.882 2.47 ]
 [0.179 3.973 3.154 5.169 3.057 4.689]
 [3.006 5.    0.094 4.987 1.098 0.926]
 [5.044 3.94  1.198 1.158 3.895 0.   ]]
4.329
